# Generated by Django 2.2.6 on 2019-10-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='编号')),
                ('classes_begin_date', models.DateField(blank=True, default='2019-09-01', null=True, verbose_name='开班时间')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], max_length=1, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(default=20, verbose_name='年龄')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('native_place', models.CharField(blank=True, max_length=30, null=True, verbose_name='籍贯')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ/微信')),
                ('business_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='业务类型')),
                ('agent', models.CharField(blank=True, max_length=30, null=True, verbose_name='代理商')),
                ('to_b_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='TO-B类型')),
                ('school_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='学校名称')),
                ('major', models.CharField(blank=True, max_length=30, null=True, verbose_name='专业')),
                ('stu_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='学号')),
                ('other', models.TextField(blank=True, null=True, verbose_name='其他')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除')),
            ],
        ),
    ]
